### ISSUE TITLE
user-can-search-for-recreational-activities-by-city-name

### ISSUE THREAD

**Issue by Mohamed-Elmessiry** [Mohamed-Elmessiry/tripster#1]
## 📐 Functionality

Users can search for recreational activities by city name

## 🖼️ Wireframes

<img width="1440" alt="Screen Shot 2021-05-24 at 8 29 38 PM" src="https://user-images.githubusercontent.com/69738204/119422552-5da0bf00-bccf-11eb-9d02-5d82a0086d24.png">
<img width="1440" alt="Screen Shot 2021-05-24 at 8 32 32 PM" src="https://user-images.githubusercontent.com/69738204/119422565-6396a000-bccf-11eb-81d8-e6589dfd23c0.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` 
- [x] Test with HTTPie
- [x]  Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to search 
- [x] Populate results using react dom to include name , picture, and address
- [x] style elements according to the wireframes

🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
