### ISSUE TITLE
User can display venue details

### ISSUE THREAD

**Issue by Mohamed-Elmessiry** [Mohamed-Elmessiry/tripster#2]
## ⚙️ Feature![image](https://user-images.githubusercontent.com/69738204/120394021-dff93680-c300-11eb-99ee-b2dc88cc9713.png)
User will have the ability to display details of a single venue 

## 📐 Functionality

The user will have the ability to select a venue from a list, which would dictate a view for the venue selected

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/69738204/120394021-dff93680-c300-11eb-99ee-b2dc88cc9713.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] add an onclick event to the image
- [x] create a function to match the id of the image
- [x] route to the webpage using the id
- [ ] render the buttons for save and add to favorites

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
