### ISSUE TITLE
User can delete venue from favorites

### ISSUE THREAD

**Issue by Mohamed-Elmessiry** [Mohamed-Elmessiry/tripster#3]
## ⚙️ Feature
The user will have the ability to save the venue to favorites, after selecting it from a single venue display

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/69738204/120868816-de2ead80-c562-11eb-9425-0802014a4c29.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database
- [ ] Update database
- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Add a post and a get method to create favorites
- [ ] Install SQL lite package
- [ ] add a get method for users
- [ ] add a single  username 
- [ ] add a app.post method for users
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a user login
- [ ] create an on-click event for the save button
- [ ] Create a function to save the venue's details in the database 
- [ ] style according to wireframes

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
